// Block types: h (section heading), sub (sub-heading), p (paragraph),
// ul (bullet list), table (head + rows).
export const intro = [
  { p: 'Last Updated: 17-08-2026' },
  { sub: 'Preamble' },
  {
    p: 'These Terms of Use ("Terms") constitute an electronic record within the meaning of the Information Technology Act, 2000 ("IT Act") and the rules made thereunder, as amended from time to time. These Terms are (i) published in accordance with Rule 3(1)(a) of the Information Technology (Intermediary Guidelines and Digital Media Ethics Code) Rules, 2021 ("Intermediary Guidelines"), and (ii) generated by a computer system and do not require any physical, electronic, or digital signature.',
  },
  {
    p: 'Please read these Terms carefully. This is a legally binding agreement between you — the person who accesses, browses, registers on, or otherwise uses the Fixxly platform, whether as an individual, an everyday retail customer, or as an authorized representative of a business ("User", "you", "your") — and Fixxly Private Limited, a company incorporated under the laws of India, having its registered office at 4th Floor, Central Mall, 2nd Phase, JP Nagar, Bengaluru, Karnataka, 560041 ("Company", "Fixxly", "we", "us", "our"), governing your use of Fixxly\'s mobile application and website (together, the "Platform") and the services made available through it (the "Services").',
  },
  {
    p: 'Separately, Velobrix Retail Private Limited ("Velobrix", "Seller"), an independent Indian company registered under GSTIN 29AAMCV4271F1ZY, having its registered office at Bay 4, 4th Floor, Nos. 45/1 and 45/2, Mantri Junction, 45th Cross, JP Nagar Phase 2, Bengaluru, Bengaluru Urban, Karnataka 560078, is the entity that sells, invoices, and delivers the products you order through the Platform, and is the counterparty to the contract of sale for any such product. Fixxly operates the Platform as a technology and order-facilitation service; while Fixxly may, on a business-to-business basis, procure trade essentials from suppliers and manufacturers for onward wholesale supply to Velobrix, Fixxly is not the seller of record for, and does not itself sell, any product to Users. See Clause 4.1 for further detail on the relationship between Fixxly and Velobrix.',
  },
  {
    p: 'By accessing, browsing, or registering on the Platform, or by placing an order or availing any Service, you agree to be bound by these Terms, our Privacy Policy, and any additional terms applicable to specific Services, together the "Agreement". If you do not agree, please do not access or use the Platform.',
  },
  {
    p: 'We may amend, restate, or replace these Terms at any time by posting the updated version on the Platform, with the "Last Updated" date revised accordingly. Your continued use of the Platform after such changes constitutes your acceptance of the amended Terms.',
  },
]

export const sections = [
  {
    h: '1. Introduction & Binding Agreement',
    blocks: [
      {
        p: '1.1 These Terms, together with the Privacy Policy and any other policies referenced herein, form a legally enforceable contract under the Indian Contract Act, 1872, executed and recorded electronically in accordance with the IT Act. No physical or digital signature is required for this Agreement to be binding.',
      },
      {
        p: '1.2 In the event of any conflict between these Terms and any additional terms applicable to a specific Service or feature, the additional terms shall prevail to the extent of such conflict.',
      },
      {
        p: '1.3 If any part of these Terms is not accepted by you, you must immediately discontinue use of the Platform.',
      },
    ],
  },
  {
    h: '2. Eligibility to Use',
    blocks: [
      {
        p: '2.1 Who the Platform is For: Fixxly\'s Services are designed and prioritized primarily for trade professionals and businesses — including plumbers, electricians, carpenters, painters, contractors, and similar tradespeople procuring materials for their work ("Business Users"). The Platform is also currently accessible to individual, non-trade customers ordering for personal use ("Retail Users"); Fixxly does not, at present, restrict access solely to Business Users, though certain features, pricing, and the liability terms differ depending on your classification as described in Clause 5.3.',
      },
      { p: 'You represent and warrant that:' },
      {
        ul: [
          'You are at least 18 years of age and are competent to enter into a binding contract under the Indian Contract Act, 1872;',
          'You are a citizen or resident of India, or a business entity duly incorporated/registered under the laws of India, using the Platform for a location within India;',
          'You will not allow any third party to access or operate your account on your behalf, and you shall not create more than one account without our prior written approval;',
          'The Platform is not intended for and may not be used by minors (persons under 18 years of age). If we become aware that an account belongs to a minor, we reserve the right to immediately suspend or terminate such account.',
          'You shall not host, display, upload, download, modify, publish, transmit, update or share any information which (i) belongs to another person and to which the User does not have any right; (ii) is obscene, pornographic, paedophilic, invasive of another\'s privacy including bodily privacy, insulting or harassing on the basis of gender, racially or ethnically objectionable, relating or encouraging money laundering or gambling or an online game that causes user harm, or promoting enmity between different groups on the grounds of religion or caste with the intent to incite violence; (iii) is harmful to child; (iv) infringes any patent, trademark, copyright or other proprietary rights; (v) deceives or misleads the addressee about the origin of the message or knowingly and intentionally communicates any misinformation or information which is patently false and untrue or misleading in nature; (vi) impersonates another person; (vii) threatens the unity, integrity, defence, security or sovereignty of India, friendly relations with foreign States, or public order, or causes incitement to the commission of any cognisable offence, or prevents investigation of any offence, or is insulting other nation; (viii) contains software virus or any other computer code, file or program designed to interrupt, destroy or limit the functionality of any computer resource; and (ix) violates any law for the time being in force.',
        ],
      },
    ],
  },
  {
    h: '3. User Account Registration',
    blocks: [
      {
        p: '3.1 Accuracy of Information: You agree that all information provided by you at the time of registration and thereafter — including KYC details, business/trade information, contact number, delivery address(es), and GST details (where applicable) — is true, accurate, current, and complete. You must promptly update any change to such information.',
      },
      {
        p: '3.2 OTP and Account Security: Access to your account is secured through a One-Time Password (OTP) and/or password linked to your registered mobile number. You are solely responsible for maintaining the confidentiality of your login credentials and OTP, and for all activity that occurs under your account, whether or not authorized by you. Notify us immediately at appsupport@fixxly.in if you suspect unauthorized use of your account.',
      },
      {
        p: '3.3 Right to Suspend: We reserve the right, at our sole discretion and without prior notice, to suspend, restrict, or terminate your account if:',
      },
      {
        ul: [
          '(a) information provided by you is found to be false, inaccurate, or misleading;',
          '(b) we have reasonable grounds to suspect fraudulent, abusive, or unlawful activity;',
          '(c) you breach any provision of these Terms; or',
          '(d) required to do so by applicable law or a competent authority.',
        ],
      },
    ],
  },
  {
    h: '4. Platform Services & User Obligations',
    blocks: [
      {
        p: '4.1 Role of Fixxly and Velobrix: Fixxly is a hyperlocal, technology-enabled platform that facilitates the discovery and ordering of trade essentials (including plumbing, electrical, carpentry & hardware, paint & finishes, power tools, and safety/PPE products) for delivery to your designated address or job site. Delivery is arranged by Velobrix through independent third-party logistics and delivery partners engaged by Velobrix ("Partners"), such as third-party logistics providers.',
      },
      {
        p: 'All products made available on the Platform — whether fulfilled from a Velobrix-operated dark store/hub or drop-shipped from a third-party supplier — are procured and sold to you exclusively by Velobrix, an independent Indian company that is not affiliated with or owned by Fixxly. Fixxly may, on a business-to-business basis, procure trade essentials from suppliers and manufacturers and on-supply them to Velobrix on a wholesale basis; however, as between Fixxly and you, Fixxly does not at any point come into or take possession of any product for the purpose of selling it to you, nor does it at any point gain title to, or have any rights or claims over, products sold to you. The contract of sale, including all representations, warranties, and product title, is exclusively between you and Velobrix. Fixxly is not the manufacturer, retailer, or seller of record for any product listed on, or sold through, the Platform, and acts solely as a technology facilitator that enables discovery and order placement and connects you to Velobrix, which arranges delivery of your order through the Partners engaged by it.',
      },
      {
        p: '4.2 Availability: Services are currently available only in the cities/zones designated on the Platform and are subject to Partner and Velobrix availability. We do not guarantee uninterrupted availability of any product, hub, Velobrix, or Partner at all times.',
      },
      {
        p: '4.3 Order Accuracy: You are responsible for accurately specifying the product, quantity, delivery address, and any other order details. We may, but are not obligated to, verify order details before dispatch.',
      },
      {
        p: '4.4 Delivery Point & Offloading Framework: Standard delivery execution across the Platform is strictly designated as a "Curbside or Ground-Floor Gate Drop-off". Partners are not structurally obligated to transport heavy bulk cargo, hazardous chemicals, or high-volume building materials into inner job sites, building blocks, trenches, or upper construction floors.',
      },
      {
        ul: [
          'Exception for Lighter Parcels: For lighter items, hand tools, or compact trade essentials, the delivery Partner may, at their discretion and in alignment with you at the destination site, carry the package to your specific floor or immediate doorstep. You are responsible for ensuring that the destination site provides a safe operational environment, free from structural hazards, for the Partner to complete such drop-offs.',
          'Courtesy Deliveries Are at Your Own Risk: Any delivery beyond the standard curbside/ground-floor drop-off point is offered solely at the Partner\'s discretion as a courtesy, does not create an ongoing obligation for future orders, and is undertaken at your own risk. Fixxly disclaims all liability for any loss, damage, or injury arising from such courtesy deliveries, save that this shall not limit your indemnification obligations under Clause 9 for any injury or loss suffered by a Partner due to unsafe conditions at your site.',
        ],
      },
      {
        p: '4.5 Prohibited Items: You shall not use the Platform to order, request delivery of, or facilitate the transport of:',
      },
      {
        ul: [
          '(a) any item that is illegal, stolen, counterfeit, or dealt with in violation of applicable law;',
          '(b) explosives, firearms, weapons, or hazardous/dangerous chemicals not permitted for transport by common carrier;',
          '(c) narcotics, psychotropic substances, or other items restricted under the Narcotic Drugs and Psychotropic Substances Act, 1985;',
          '(d) any item whose sale, possession, or transport is restricted or prohibited under any law, rule, or regulation in force, including transport/railway/airport authority restrictions.',
        ],
      },
      {
        p: 'Note: We reserve the right to inspect, refuse, or report to the appropriate authorities any shipment reasonably suspected of containing prohibited items, and to take legal action against the User responsible.',
      },
      {
        p: '4.6 Conduct with Partners: You agree to behave professionally and courteously with delivery and service Partners. Verbal abuse, physical misconduct, or harassment of a Partner is a material breach of these Terms and may result in immediate suspension of your account, in addition to any other legal remedies available to us or the affected Partner.',
      },
      {
        p: '4.7 Location Access: To dispatch orders accurately and provide real-time tracking, the Platform requires access to your device\'s location ("GPS"). Where you enable background location access, this may be used to improve dispatch accuracy and delivery estimated time of arrivals even when the app is not actively open. You may disable location permissions through your device settings, though this may limit or disable certain Services. See our Privacy Policy for further detail.',
      },
      {
        p: '4.8 No Unauthorized Use: You shall not use any bot, scraper, or automated means to access the Platform, attempt to reverse-engineer any part of the Platform, or use the Platform for any purpose that competes with Fixxly\'s business.',
      },
      {
        p: '4.9 Intellectual Property Safe Harbor & Takedown: Fixxly operates as an intermediary under Section 79 of the IT Act. If you are a brand owner or authorized representative and believe any Seller listing violates your intellectual property rights, you must submit a formal notice to our Grievance Officer containing: (a) description of the work infringed, (b) URL/listing location, and (c) proof of ownership. Fixxly will review and remove compliant infringing content within 36 hours in accordance with applicable laws.',
      },
    ],
  },
  {
    h: '5. Fees, Taxes, and Payment',
    blocks: [
      {
        p: '5.1 Pricing Display: The price of products and applicable delivery fee will be displayed on the Platform at the time of placing an order. Prices are set by Velobrix, are subject to change without prior notice, and the price applicable is the one displayed at the time your order is confirmed.',
      },
      {
        p: '5.2 Taxes: Unless stated otherwise, prices displayed are exclusive of applicable Goods and Services Tax (GST) and any other statutory levy, which shall be charged additionally and reflected in your invoice.',
      },
      {
        p: '5.3 Business User / Retail User Classification & GST Verification: The Platform provides systemic "GST inputs and prompts" at various stages of the user journey to facilitate seamless business invoicing.',
      },
      {
        ul: [
          'How You\'re Classified: Your classification as a Business User or Retail User (as defined in Clause 2.1, and as referenced in the liability terms at Clause 8.4) is determined at the account level based on the profile details you provide at registration and/or whether a valid GSTIN is verified on file for your account.',
          'Lightweight Portal Validation: Fixxly processes GSTIN details through automated API validation loops via the GST portal to verify the structural existence, status, and legal composition format of the business information you submit. You are solely responsible for ensuring the absolute accuracy of the business profile details. Fixxly disclaims all tax-compliance liabilities, and any penalties arising from false configurations will be subject to indemnity under Section 9.',
          'Commercial Acknowledgment: If you are classified as, or hold yourself out to be, a Business User, you acknowledge and agree that you are purchasing goods in a commercial capacity for your trade, business, or contracting operations.',
          'Retail Invoicing: If you are classified as a Retail User, you acknowledge that your purchases are for personal use, and you agree to receive a retail consumer invoice with standard consumer tax applications.',
          'Invoice Issuance: All GST or retail tax invoices for products purchased through the Platform are issued by Velobrix, as the seller of record, based on the account and business details verified against your profile.',
          'Reclassification: Where your ordering pattern is materially inconsistent with your declared classification (for example, a Retail User placing recurring bulk or commercial-volume orders), Fixxly reserves the right to reclassify your account as a Business User for the purposes of Clause 8.4, with notice to you.',
        ],
      },
      {
        p: '5.4 Payment Methods: You may pay through the payment options made available on the Platform, including UPI, debit/credit cards, net banking, wallets, or Cash on Delivery (COD), where offered. Online payments on the Platform are processed through a payment aggregator authorised by the Reserve Bank of India and engaged by Velobrix from time to time ("Payment Gateway"). The merchant of record and beneficiary for all such payments is Velobrix, as the seller of the products ordered by you; Fixxly does not receive, hold, or have access to your payment or the sale proceeds at any point. You hereby agree and acknowledge that the payment facility made available on the Platform is neither a banking nor a financial service, but is provided by the Payment Gateway as a licensed intermediary for the electronic collection and remittance of payments to Velobrix using existing authorised banking infrastructure and card network rails. Neither Fixxly nor the Payment Gateway acts as trustee or in a fiduciary capacity with respect to the transaction or the transaction price.',
      },
      {
        p: '5.5 Cash on Delivery: Where you select cash on delivery ("COD"), payment is due in full to the delivery Partner, on behalf of Velobrix, at the time of delivery. If the recipient refuses or is unable to make payment, we reserve the right to withhold delivery of the order and/or levy a cancellation or non-delivery charge.',
      },
      {
        p: '5.6 Tax Deduction at Source: Where any deduction or withholding of tax is required to be made by you under applicable law, you shall furnish evidence of such deduction to us within the timelines prescribed under applicable law.',
      },
      {
        p: '5.7 Discrepancies: Any weight, quantity, or price discrepancy identified at the packing hub shall be communicated to you, and additional charges (if any) may be levied, which you authorize us to collect.',
      },
      {
        p: '5.8 Input Tax Credit (ITC) Disclaimer: Velobrix issues GST invoices for products purchased through the Platform, and Fixxly is not involved in and does not verify the invoicing process. Fixxly is not responsible or liable for ensuring that Velobrix uploads the invoice to the GST portal or deposits the tax collected. Fixxly explicitly disclaims all liability for any loss of ITC suffered by a Business User due to any default, non-compliance, or omission by Velobrix.',
      },
      {
        p: '5.9 Typographical & Pricing Errors: If a product is listed at an incorrect price or with incorrect structural details due to a typographical error or technical glitch, Fixxly and Velobrix reserve the right to cancel any orders placed for that item, regardless of whether the order has been confirmed or payment has been processed. In such cases, a full refund will be processed to the User by Velobrix.',
      },
      {
        p: '5.10 Seller Information: In accordance with the Consumer Protection (E-Commerce) Rules, 2020, the seller of the products offered on the Platform is: Velobrix Retail Private Limited, registered office at Bay 4, 4th Floor, Nos. 45/1 and 45/2, Mantri Junction, 45th Cross, JP Nagar Phase 2, Bengaluru, Bengaluru Urban, Karnataka 560078; GSTIN 29AAMCV4271F1ZY; CIN [•]. For queries relating to your order, product, or a purchase from Velobrix, you may contact us at care@fixxly.in or +91-6364243131, and such queries will be routed to Velobrix as necessary.',
      },
    ],
  },
  {
    h: '6. Cancellation & Refund Policy',
    blocks: [
      {
        p: 'In brief: You can cancel most orders free of charge within the window shown at checkout. Cancelling after an order has been packed or dispatched may attract a cancellation fee. Refunds for eligible cancellations are processed to your original payment method.',
      },
      {
        p: '6.1 Definition of Business Day: For the purposes of processing timelines, service window metrics, and financial SLAs under this Agreement, a "Business Day" shall mean Monday through Saturday, from 09:00 AM to 06:00 PM IST, excluding days on which banking institutions in Karnataka, India are authorized or obligated under applicable law to remain closed.',
      },
      {
        p: '6.2 User-Initiated Cancellation: You may cancel an order without charge within the time window specified on the Platform at the time of placing the order (typically before the order is packed). Cancellations requested after this window, including after the order has been packed or dispatched, may attract a cancellation fee, which will be displayed to you before you confirm the cancellation.',
      },
      {
        p: '6.3 Company-Initiated Cancellation: We may cancel an order, in full or in part, for reasons including but not limited to:',
      },
      {
        ul: [
          '(a) unavailability of stock from Velobrix or a delivery Partner;',
          '(b) the delivery address being outside our current serviceable zone;',
          '(c) failure to reach you for order confirmation;',
          '(d) suspected fraudulent, prohibited, or Terms-violating activity connected to the order;',
          '(e) the delivery Partner being unable to complete the delivery at the standard curbside/ground-floor drop-off point (Clause 4.4) despite reasonable attempts to reach you or a representative at the site;',
          '(f) circumstances beyond our reasonable control.',
        ],
      },
      {
        p: 'Where your order is cancelled under this clause, you will not be charged, and any amount already paid will be refunded by Velobrix to your original payment method.',
      },
      {
        p: '6.4 Refund Timelines: Approved refunds will be initiated by Velobrix within [3] Business Days of the cancellation or return verification being formally approved, and may take an additional 5–7 banking days to reflect in your account depending on your payment provider.',
      },
      {
        p: '6.5 Evidence-Based Return & Defect Reporting Framework: If you receive a damaged, defective, completely incorrect item, or find items missing from your order, you must report the issue through the Platform within [24] hours of delivery to be eligible for a replacement or refund, subject to a strict verification framework:',
      },
      {
        ul: [
          'Mandatory Digital Evidence: To prevent fraudulent optimization loops, Users must upload 7-8 clear, unedited photographic images or a continuous unboxing video depicting the outer container box, the inner packaging components, the shipping label/invoice sticker, and the specific structural defect or mismatch area. Missing product or volume claims will not be evaluated without baseline package weight and label validation pictures.',
          'Category Exclusions for Industrial Trade Essentials: Given the operational safety thresholds of construction and building supplies, returns or exchanges will be rejected if the item has been partially unboxed, installed, utilized on-site, or structurally mixed.',
          'Strict Non-Returnable Categories: Open bags of cement, sand, primers, adhesives, cut lengths of cabling or piping, custom made-to-order tints or finishes, and used safety/PPE items are strictly non-returnable and non-refundable unless verified as completely incorrect or damaged prior to offloading at the curbside.',
        ],
      },
      {
        p: '6.6 Failed Delivery Attempts & Restocking Fees: If a delivery attempt fails because: (1) the User or their representative is unavailable at the job site after the platform arrival alert, (2) the User provides an incorrect delivery location, or (3) the User refuses offloading at the curbside, the delivery fee for that specific order shall be completely forfeited. Fixxly reserves the right to charge a Restocking Fee equal to up to 20% of the order value for heavy bulk materials or custom-packed goods before scheduling a re-delivery.',
      },
    ],
  },
  {
    h: '7. Intellectual Property Rights',
    blocks: [
      {
        p: '7.1 All content on the Platform — including the Fixxly name, logo, brand assets, software, source code, user interface, design, and compilation of product listings — is the exclusive property of Fixxly or its licensors and is protected under applicable copyright, trademark, and other intellectual property laws.',
      },
      {
        p: '7.2 You may not copy, reproduce, modify, distribute, publicly display, or create derivative works from any Platform content without our prior written consent.',
      },
      {
        p: '7.3 Any feedback, reviews, or content you submit on the Platform grants Fixxly a non-exclusive, royalty-free, worldwide, sub-licensable license to use, reproduce, and display such content in connection with operating and promoting the Platform.',
      },
      {
        p: '7.4 Nothing in these Terms transfers any ownership of Fixxly\'s intellectual property to you.',
      },
    ],
  },
  {
    h: '8. Disclaimer of Warranties & Limitation of Liability',
    blocks: [
      { p: 'Please read this section carefully — it limits our liability to you.' },
      {
        p: '8.1 The Platform and Services are provided on an "as is" and "as available" basis, without warranties of any kind, whether express or implied, including warranties of merchantability, fitness for a particular purpose, or non-infringement, to the maximum extent permitted by applicable law.',
      },
      {
        p: '8.2 We do not guarantee that the Platform will be uninterrupted, error-free, or that all products displayed will be available at all times.',
      },
      {
        p: '8.3 Third-Party Partners & Product Quality Disclaimer: Delivery Partners and Velobrix are independent third parties and not employees or agents of Fixxly. Fixxly does not manufacture, test, or certify any industrial trade essentials (including electrical load limits, structural integrity, ISI/BIS marks, tool calibrations, or safety thresholds). All warranties, item descriptions, and product certifications are carried exclusively by the respective third-party manufacturer or Velobrix, as seller. Fixxly is not liable for any act, omission, negligence, product defect, or misconduct of a Partner or Velobrix, though we will make reasonable efforts to assist in resolving any dispute raised in good faith.',
      },
      {
        p: '8.4 Tiered Limitation of Liability: Subject to applicable Indian laws and notwithstanding anything contained in this Agreement, and based on your validation classification under Clause 5.3:',
      },
      {
        ul: [
          'For Retail Users: Fixxly\'s maximum aggregate liability arising out of or relating to any order, defect, or Platform service failure shall be strictly limited to a refund of the actual purchase price paid by you for the specific affected item(s).',
          'For Business Users: Fixxly shall not be held liable for any indirect, special, incidental, consequential, or punitive damages — including but not limited to site construction delays, labor idle-time, project penalties, material waste, structural failures, or loss of commercial profit. Our aggregate liability for Business User transactions shall never exceed the greater of (i) the delivery fee paid for that specific order, and (ii) INR 500 (Rupees Five Hundred only), so that this cap always retains a meaningful floor regardless of any promotional or waived delivery fee.',
        ],
      },
      {
        p: '8.5 Nothing in this section shall exclude or limit liability that cannot be excluded or limited under applicable Indian law.',
      },
    ],
  },
  {
    h: '9. Indemnification',
    blocks: [
      {
        p: 'You agree to indemnify, defend, and hold harmless Fixxly, Velobrix, and each of their respective affiliates, officers, directors, employees, and agents ("Indemnitees") from and against any losses, liabilities, claims, damages, costs, and expenses (including reasonable legal fees) arising out of or in connection with:',
      },
      {
        ul: [
          'your breach of any provision of these Terms;',
          'your violation of any applicable law or third-party right in connection with your use of the Platform;',
          'any misrepresentation or inaccurate information provided by you (including inaccurate classification, business/trade details, or GST information under Clause 5.3);',
          'any shipment or order placed by you that is found to contain a prohibited, illegal, or restricted item;',
          'your misconduct towards a delivery or service Partner, or any unsafe condition at your site that results in loss or injury to a Partner in connection with a delivery, including a courtesy delivery under Clause 4.4.',
        ],
      },
      {
        p: 'This indemnification obligation shall survive the termination of your account or these Terms.',
      },
    ],
  },
  {
    h: '10. Governing Law & Jurisdiction',
    blocks: [
      {
        p: 'These Terms shall be governed by and construed in accordance with the laws of India. Subject to Clause 11 (Grievance Redressal) below, courts at Bengaluru, Karnataka shall have exclusive jurisdiction over any dispute arising out of or in connection with these Terms.',
      },
    ],
  },
  {
    h: '11. Grievance Redressal Mechanism',
    blocks: [
      {
        p: 'In accordance with the IT Act, 2000, the Intermediary Guidelines, and the Digital Personal Data Protection Act, 2023, the details of our Grievance Officer are set out below. The Grievance Officer will acknowledge your complaint within 24 hours and endeavour to resolve it as expeditiously as possible, not exceeding 7 days from receipt.',
      },
      {
        table: {
          head: ['Particular', 'Detail'],
          rows: [
            ['Name', 'Sarthak Patnaik'],
            ['Designation', 'Grievance Officer'],
            ['Address', '4th Floor, Central Mall, 2nd Phase, JP Nagar, Bengaluru, Karnataka, 560041'],
            ['Email', 'appsupport@fixxly.in'],
            ['Phone', '+91-9740833777'],
            ['Working hours', 'Mon–Sat, 9 AM – 6 PM (Business Days)'],
          ],
        },
      },
    ],
  },
  {
    h: '12. Force Majeure',
    blocks: [
      {
        p: 'Fixxly shall not be liable for any delay, failure, or disruption in the Services resulting from causes beyond its reasonable control, including acts of God, fire, flood, war, riot, strike, epidemic/pandemic, governmental action, internet or telecommunications failure, or non-performance by a third party.',
      },
    ],
  },
  {
    h: '13. Miscellaneous',
    blocks: [
      {
        p: '13.1 Severability: If any provision of these Terms is held invalid or unenforceable, the remaining provisions shall continue in full force and effect.',
      },
      {
        p: '13.2 Assignment: Fixxly may assign these Terms, in whole or in part, to any affiliate or successor entity. You may not assign your rights or obligations under these Terms without our prior written consent.',
      },
      {
        p: '13.3 Independent Contractors: Nothing in these Terms creates any employment, agency (except as expressly provided), partnership, or joint venture relationship between you and Fixxly.',
      },
      {
        p: '13.4 Entire Agreement: These Terms, together with the Privacy Policy and any other applicable policies, constitute the entire agreement between you and Fixxly regarding your use of the Platform, superseding any prior agreements.',
      },
      {
        p: '13.5 Notices: All notices to Fixxly must be sent in writing to the Grievance Officer\'s address above. Notices to you may be sent via email, SMS, WhatsApp, in-app notification, or by posting on the Platform.',
      },
    ],
  },
]

export const contact = {
  company: 'Fixxly Private Limited',
  address: '4th Floor, Central Mall, 2nd Phase, JP Nagar, Bengaluru, Karnataka, 560041',
  email: 'appsupport@fixxly.in',
  website: 'https://www.fixxly.in',
}
