// Block types: h (section heading), sub (sub-heading), p (paragraph), ul (bullet list).
export const intro = [
  {
    p: 'These Terms of Use ("Terms") constitute an electronic record within the meaning of the Information Technology Act, 2000 ("IT Act") and the rules made thereunder, as amended from time to time. These Terms are (i) published in accordance with Rule 3(1)(a) of the Information Technology (Intermediary Guidelines and Digital Media Ethics Code) Rules, 2021 ("Intermediary Guidelines"), and (ii) generated by a computer system and do not require any physical, electronic, or digital signature.',
  },
  {
    p: 'Please read these Terms carefully. This is a legally binding agreement between you, the person who accesses, browses, or registers on the Fixxly mobile application ("User", "you", "your"), and Fixxly Private Limited, a company incorporated under the laws of India, having its registered office at 4th Floor, Central Mall, 2nd Phase, JP Nagar, Bengaluru, Karnataka, 560041 ("Company", "Fixxly", "we", "us", "our"), governing your use of the Fixxly mobile application (the "App") and the features made available through it.',
  },
  {
    p: 'This version of the App is a product discovery and catalogue platform. It allows you to sign in, browse categories and products, save profile and view GST information. Ordering, payments, and delivery are not offered through this version of the App.',
  },
  {
    p: 'By accessing, browsing, or registering on the App, you agree to be bound by these Terms and our Privacy Policy (together, the "Agreement"). If you do not agree, please do not access or use the App.',
  },
  {
    p: 'We may amend, restate, or replace these Terms at any time by posting the updated version, with the "Last Updated" date revised accordingly. Your continued use of the App after such changes constitutes your acceptance of the amended Terms.',
  },
]

export const sections = [
  {
    h: '1. Introduction and Binding Agreement',
    blocks: [
      {
        p: '1.1 These Terms, together with the Privacy Policy and any other policies referenced herein, form a legally enforceable contract under the Indian Contract Act, 1872, executed and recorded electronically in accordance with the IT Act. No physical or digital signature is required for this Agreement to be binding.',
      },
      {
        p: '1.2 In the event of any conflict between these Terms and any additional terms applicable to a specific feature, the additional terms shall prevail to the extent of such conflict.',
      },
      {
        p: '1.3 If any part of these Terms is not accepted by you, you must immediately discontinue use of the App.',
      },
    ],
  },
  {
    h: '2. Eligibility to Use',
    blocks: [
      {
        p: '2.1 Who the App is for. Fixxly is designed and prioritised primarily for trade professionals and businesses, including plumbers, electricians, carpenters, painters, contractors, and similar tradespeople who browse and procure in-home and construction materials for their work. Access is not, at present, restricted solely to trade professionals.',
      },
      { p: 'You represent and warrant that:' },
      {
        p: '2.2 You are at least 18 years of age and are competent to enter into a binding contract under the Indian Contract Act, 1872;',
      },
      {
        p: '2.3 You are a citizen or resident of India, or a business entity duly incorporated or registered under the laws of India, using the App for a location within India;',
      },
      {
        p: '2.4 You will not allow any third party to access or operate your account on your behalf, and you shall not create more than one account without our prior written approval;',
      },
      {
        p: '2.5 The App is not intended for and may not be used by minors (persons under 18 years of age). If we become aware that an account belongs to a minor, we reserve the right to immediately suspend or terminate such account.',
      },
      {
        p: "2.6 Content and conduct. To the extent the App allows you to submit any content (for example, a name, a site label, or a review), you shall not upload, publish, or share any information that: (i) belongs to another person and to which you have no right; (ii) is obscene, defamatory, harassing, or invasive of another's privacy; (iii) is harmful to a child; (iv) infringes any patent, trademark, copyright, or other proprietary right; (v) is knowingly false or misleading; (vi) impersonates another person; (vii) threatens the unity, integrity, defence, security, or sovereignty of India or public order; (viii) contains any software virus or code designed to interrupt or damage any computer resource; or (ix) violates any law for the time being in force.",
      },
    ],
  },
  {
    h: '3. User Account and Registration',
    blocks: [
      {
        p: '3.1 Accuracy of information. You agree that all information you provide, including your contact number and, where you choose to add them, your name, business or trade details, and GST details, is true, accurate, current, and complete. You must promptly update any change to such information.',
      },
      {
        p: '3.2 OTP and account security. Access to your account is secured through a One-Time Password (OTP) linked to your registered mobile number. You are solely responsible for maintaining the confidentiality of your credentials and OTP, and for all activity that occurs under your account. Notify us immediately at appsupport@fixxly.in if you suspect unauthorised use of your account.',
      },
      {
        p: '3.3 Right to suspend. We reserve the right, at our sole discretion and without prior notice, to suspend, restrict, or terminate your account if: (a) information provided by you is found to be false, inaccurate, or misleading; (b) we have reasonable grounds to suspect fraudulent, abusive, or unlawful activity; (c) you breach any provision of these Terms; or (d) we are required to do so by applicable law or a competent authority.',
      },
    ],
  },
  {
    h: '4. The App and Permitted Use',
    blocks: [
      {
        p: '4.1 Nature of the App. The App is a technology platform that enables you to discover and browse trade and in-home materials (including plumbing, electrical, paint and finishes, hardware and tools, and related products) offered by independent third-party brands and sellers ("Sellers"). The App displays product listings, prices, and product information that are sourced from, and are the responsibility of, those third parties. Fixxly is not the manufacturer or seller of record for the products displayed in the App.',
      },
      {
        p: '4.2 No ordering, payment, or delivery in this version. This version of the App does not process orders, collect payments, or arrange delivery. No payment information is requested or processed through the App. Where any transactional feature is introduced in future, it will be governed by additional terms presented to you at that time.',
      },
      {
        p: '4.3 Product information is indicative. Product listings, specifications, images, availability, and prices shown in the App are provided are indicative, and may be incomplete, inaccurate, or out of date. We do not warrant the accuracy of such information and you should verify details independently before relying on them. We may correct any error and update listings at any time without notice.',
      },
      {
        p: "4.4 Acceptable use. You shall not: (a) use any bot, scraper, crawler, or automated means to access the App or its data; (b) attempt to reverse-engineer, decompile, or extract the source code of any part of the App; (c) use the App for any purpose that competes with Fixxly's business; or (d) use the App for any unlawful purpose or in violation of these Terms.",
      },
      {
        p: '4.5 Intellectual property safe harbour and takedown. Fixxly operates as an intermediary under Section 79 of the IT Act. If you are a brand owner or authorised representative and believe any listing infringes your intellectual property rights, you may submit a notice to our Grievance Officer containing: (a) a description of the work infringed, (b) the location of the listing, and (c) proof of ownership. We will review and act on compliant notices in accordance with applicable law.',
      },
      {
        p: '4.6 Availability. The App and its features are provided on an "as available" basis. We do not guarantee uninterrupted availability of the App, any product, or any feature, and we may add, modify, suspend, or discontinue any feature at any time.',
      },
    ],
  },
  {
    h: '5. Intellectual Property Rights',
    blocks: [
      {
        p: '5.1 All content in the App, including the Fixxly name, logo, brand assets, software, source code, user interface, design, and the compilation of product listings, is the exclusive property of Fixxly or its licensors and is protected under applicable copyright, trademark, and other intellectual property laws.',
      },
      {
        p: '5.2 You may not copy, reproduce, modify, distribute, publicly display, or create derivative works from any App content without our prior written consent.',
      },
      {
        p: '5.3 Any feedback or content you submit grants Fixxly a non-exclusive, royalty-free, worldwide, sub-licensable licence to use, reproduce, and display such content in connection with operating and improving the App.',
      },
      {
        p: "5.4 Nothing in these Terms transfers any ownership of Fixxly's intellectual property to you.",
      },
    ],
  },
  {
    h: '6. Disclaimer of Warranties and Limitation of Liability',
    blocks: [
      {
        p: '6.1 The App is provided on an "as is" and "as available" basis, without warranties of any kind, whether express or implied, including warranties of merchantability, fitness for a particular purpose, or non-infringement, to the maximum extent permitted by applicable law.',
      },
      {
        p: '6.2 We do not guarantee that the App will be uninterrupted or error-free, or that any product information displayed is accurate, complete, or current.',
      },
      {
        p: '6.3 Third-party product information. Product descriptions, specifications, certifications, and prices are provided by independent Sellers and manufacturers, who are solely responsible for them. Fixxly does not manufacture, test, or certify any product displayed in the App and is not liable for any inaccuracy in third-party product information or for any decision you take in reliance on it.',
      },
      {
        p: "6.4 Limitation of liability. To the maximum extent permitted by applicable law, Fixxly shall not be liable for any indirect, special, incidental, consequential, or punitive damages arising out of or relating to your use of the App. Fixxly's aggregate liability arising out of or relating to the App shall not exceed INR 500 (Rupees Five Hundred only).",
      },
      {
        p: '6.5 Nothing in this section shall exclude or limit any liability that cannot be excluded or limited under applicable Indian law.',
      },
    ],
  },
  {
    h: '7. Indemnification',
    blocks: [
      {
        p: 'You agree to indemnify, defend, and hold harmless Fixxly, its affiliates, officers, directors, employees, and agents from and against any losses, liabilities, claims, damages, costs, and expenses (including reasonable legal fees) arising out of or in connection with: (a) your breach of any provision of these Terms; (b) your violation of any applicable law or third-party right in connection with your use of the App; (c) any misrepresentation or inaccurate information provided by you; or (d) any content you submit that infringes a third-party right or violates applicable law. This obligation shall survive the termination of your account or these Terms.',
      },
    ],
  },
  {
    h: '8. Governing Law and Jurisdiction',
    blocks: [
      {
        p: 'These Terms shall be governed by and construed in accordance with the laws of India. Subject to Clause 9 (Grievance Redressal) below, courts at Bengaluru, Karnataka shall have exclusive jurisdiction over any dispute arising out of or in connection with these Terms.',
      },
    ],
  },
  {
    h: '9. Grievance Redressal Mechanism',
    blocks: [
      {
        p: 'In accordance with the IT Act, 2000, the Intermediary Guidelines, 2021, and the Digital Personal Data Protection Act, 2023, the details of our Grievance Officer are set out below.',
      },
      {
        ul: [
          'Name: Sarthak Patnaik',
          'Designation: Grievance Officer / Data Protection Contact',
          'Address: 4th Floor, Central Mall, 2nd Phase, JP Nagar, Bengaluru, Karnataka, 560041',
          'Email: appsupport@fixxly.in',
          'Phone: +91-9740833777',
          'Response Timeline: We acknowledge your complaint within 24 hours and endeavour to resolve it within 7 days from receipt, on Business Days.',
        ],
      },
    ],
  },
  {
    h: '10. Force Majeure',
    blocks: [
      {
        p: 'Fixxly shall not be liable for any delay, failure, or disruption in the App resulting from causes beyond its reasonable control, including acts of God, fire, flood, war, riot, strike, epidemic or pandemic, governmental action, internet or telecommunications failure, or non-performance by a third party.',
      },
    ],
  },
  {
    h: '11. Miscellaneous',
    blocks: [
      {
        p: '11.1 Severability. If any provision of these Terms is held invalid or unenforceable, the remaining provisions shall continue in full force and effect.',
      },
      {
        p: '11.2 Assignment. Fixxly may assign these Terms, in whole or in part, to any affiliate or successor entity. You may not assign your rights or obligations under these Terms without our prior written consent.',
      },
      {
        p: '11.3 Independent relationship. Nothing in these Terms creates any employment, agency, partnership, or joint venture relationship between you and Fixxly.',
      },
      {
        p: '11.4 Entire agreement. These Terms, together with the Privacy Policy, constitute the entire agreement between you and Fixxly regarding your use of the App, superseding any prior agreements.',
      },
      {
        p: "11.5 Notices. All notices to Fixxly must be sent in writing to the Grievance Officer's address above. Notices to you may be sent via SMS, in-app notice, or email.",
      },
    ],
  },
]

export const contact = {
  company: 'Fixxly Private Limited',
  address: '4th Floor, Central Mall, 2nd Phase, JP Nagar, Bengaluru, Karnataka, 560041',
  email: 'appsupport@fixxly.in',
  website: 'https://www.fixxly.in',
}
